language: python
python:
- '3.7'
install:
- pip install -e .
- cd develop
- python manage.py migrate
script:
- python manage.py test permafrost
- cd ..
deploy:
  provider: pypi
  user: __token__
  password:
    secure: BTyvkNcJJTT7pWaHIKC7M1lLJv9acgqids0ZTt124WJrT74E9ibCk8gNz/JQzTMBcgVw9ZJB5vExznvGYSTJlaQx/qetvTAmvNmST7TXqJH86m8fjzzP2fDivxUv7G9Y4NLCo1+SWj7U3Qs7faDw8BenJybdJZFN11PT1ktPqFxCeWnk2Sg/qcJCYZ/uFZqcMmOBFDwQta434kIjMszbdFdx+ukl15LKPNfW7l3galZhIHzRhMitzV6P3k/2yci8xGvk7WbGjHgzMjVu1gj4dd+AEYb3iYKnWUzfji3axsx3K/WnW9t3XX9n9sfGpach5nivnWpG4BpxMVD2oZcsnfbkKcazU8z4kvrHKpY64Ov6hc4ZEF/sZ0h2OwZ7HPVEqKfJdXlBnNIt0876CsSW4st0EWKXla/fkkKhNyjttlIqaXdxyc5oZYfetSKElB/glqTr57fwSZs1b9dx3NL5SjCKYgio41el8eiNuIZftYdkJLIzvwv/P5P2pyT/nm/VBsVQqmsnfdzffv15xSUgx8y8CABWF/bPaNvQ/E9t4V8/ywvthGAD/yPRpkmw5FlJufHvK45sHFrwcTPPI3HeeFCCWVw88cToNGaB+PmFEvZku2s6K4MkTajeYiY3Cesyw0HGR1QkgYPtzbonX+WYh3g7lypPFGMTnnVvdLpdzCg=
